title: "{{ syzygy_html_hostname }}"
domain: "{{ syzygy_html_domain }}"
email: "{{ syzygy_html_support_email }}"
url: "http://{{ syzygy_html_domain }}"
longname: "{{ syzygy_html_longname }}"

relative_permalinks: false

exclude: [CNAME, README.md, LICENSE, ansible.sh]
