title: "{{ syzygy_html_hostname }}"
email: "{{ syzygy_html_support_email }}"
domain: "{{ syzygy_html_domain }}"
url: "http://{{ syzygy_html_domain }}"

relative_permalinks: false

exclude: [CNAME, README.md, LICENSE, ansible.sh]
