title: "xxx-syzygy-host-xxx.syzygy.ca"
email: "jupyter@pims.math.ca"
domain: xxx-syzygy-host-xxx.syzygy.ca
url: http://xxx-syzygy-host-xxx.syzygy.ca

relative_permalinks: false

exclude: [CNAME, README.md, LICENSE, ansible.sh]
